export enum TimeSeries {
    INTRADAY = "TIME_SERIES_INTRADAY",
    DAILY = "TIME_SERIES_DAILY",
    DAILY_ADJUSTED = "TIME_SERIES_DAILY_ADJUSTED",
    WEEKLY = "TIME_SERIES_WEEKLY",
    WEEKLY_ADJUSTED = "TIME_SERIES_WEEKLY_ADJUSTED",
    MONTHLY = "TIME_SERIES_MONTHLY",
    MONTHLY_ADJUSTED = "TIME_SERIES_MONTHLY_ADJUSTED",
    ONE_DAY = "CUSTOM_ONE_DAY",
    ONE_WEEK = "CUSTOM_ONE_WEEK",
    ONE_MONTH = "CUSTOM_ONE_MONTH",
    ONE_YEAR = "CUSTOM_ONE_YEAR",
    FIVE_YEAR = "CUSTOM_FIVE_YEAR",
    QUOTE = "GLOBAL_QUOTE"
}
